import { convertBlockBody, extractBalanced, findTopLevelMembers, mapType, rustIdent, splitParams, visibility } from './common.js';

function parseKotlinFun(text) {
  const brace = text.indexOf('{');
  if (brace < 0) return null;
  const header = text.slice(0, brace).replace(/\s+/g, ' ').trim();
  const bal = extractBalanced(text, brace);
  if (!bal) return null;
  const m = header.match(/^(?<mods>(?:(?:public|private|protected|internal|open|override|suspend|inline|tailrec|operator|infix|abstract)\s+)*)?fun\s+(?<name>\w+)\s*\((?<params>.*)\)\s*(?::\s*(?<ret>[^=]+?))?$/);
  if (!m) return null;
  return { ...m.groups, mods: m.groups.mods || '', body: bal.body };
}

function convertKotlinClass(name, mods, paramsRaw, body, warnings, dataClass = false) {
  const ctorParams = splitParams(paramsRaw || '', 'kotlin');
  const members = findTopLevelMembers(body);
  const functions = [];
  const props = [];
  for (const p of (paramsRaw || '').split(',').map(x => x.trim()).filter(Boolean)) {
    const m = p.match(/^(val|var)\s+(\w+)\s*:\s*([^=]+?)(?:\s*=.*)?$/);
    if (m) props.push({ mutable: m[1] === 'var', name: m[2], type: m[3].trim() });
  }
  for (const member of members) {
    const fn = member.kind === 'block' ? parseKotlinFun(member.text) : null;
    if (fn) functions.push(fn);
    else {
      const prop = member.text.match(/^(?:public\s+|private\s+|protected\s+|internal\s+)?(val|var)\s+(\w+)\s*:\s*([^=;]+)(?:=\s*(.+?))?;?$/s);
      if (prop) props.push({ mutable: prop[1] === 'var', name: prop[2], type: prop[3].trim(), init: prop[4]?.trim() });
      else if (member.text.trim()) warnings.push(`Unsupported Kotlin class member in ${name}: ${member.text.slice(0, 80).replace(/\s+/g,' ')}`);
    }
  }
  const seen = new Set();
  const uniqueProps = props.filter(p => { if (seen.has(p.name)) return false; seen.add(p.name); return true; });
  const derives = dataClass ? '#[derive(Debug, Clone, PartialEq)]' : '#[derive(Debug, Clone)]';
  const typeVis = /\b(?:private|protected|internal)\b/.test(mods) ? '' : 'pub ';
  const out = [derives, `${typeVis}struct ${name} {`, ...uniqueProps.map(p => `    pub ${rustIdent(p.name)}: ${mapType(p.type)},`), '}', '', `impl ${name} {`];
  if (ctorParams.length || uniqueProps.length) {
    out.push(`    pub fn new(${ctorParams.map(p => `${p.name}: ${p.type}`).join(', ')}) -> Self {`, '        Self {');
    for (const p of uniqueProps) {
      const rn = rustIdent(p.name);
      if (ctorParams.some(x => x.name === rn)) out.push(`            ${rn},`);
      else if (p.init) out.push(`            ${rn}: ${p.init},`);
      else out.push(`            ${rn}: Default::default(),`);
    }
    out.push('        }', '    }', '');
  }
  for (const fn of functions) {
    const params = splitParams(fn.params, 'kotlin');
    const mutates = /\b(?:this\.)?\w+\s*=/.test(fn.body);
    const ret = mapType(fn.ret?.trim() || 'Unit');
    const fnVis = /\b(?:private|protected|internal)\b/.test(fn.mods) ? '' : 'pub ';
    out.push(`    ${fnVis}fn ${rustIdent(fn.name)}(${mutates ? '&mut self' : '&self'}${params.length ? ', ' : ''}${params.map(p => `${p.name}: ${p.type}`).join(', ')})${ret === '()' ? '' : ` -> ${ret}`} {`);
    out.push(convertBlockBody(fn.body, 'kotlin', warnings, { fieldNames: uniqueProps.map(p => p.name), paramNames: params.map(p => p.name) }) || '        // TODO: translated body was empty');
    out.push('    }', '');
  }
  out.push('}');
  return out.join('\n');
}

function convertKotlinInterface(name, mods, body, warnings) {
  const traitVis = /\b(?:private|protected|internal)\b/.test(mods) ? '' : 'pub ';
  const out = [`${traitVis}trait ${name} {`];
  const re = /fun\s+(\w+)\s*\(([^)]*)\)\s*(?::\s*([^\n{=]+))?/g;
  let m;
  while ((m = re.exec(body))) {
    const params = splitParams(m[2], 'kotlin');
    const ret = mapType((m[3] || 'Unit').trim());
    out.push(`    fn ${rustIdent(m[1])}(&self${params.length ? ', ' : ''}${params.map(p => `${p.name}: ${p.type}`).join(', ')})${ret === '()' ? '' : ` -> ${ret}`};`);
  }
  if (out.length === 1) warnings.push(`No interface functions detected in ${name}`);
  out.push('}');
  return out.join('\n');
}

export function convertKotlin(source, fileName = 'input.kt') {
  const warnings = [];
  const text = source.replace(/^\s*package\s+[\w.]+\s*$/gm, '').replace(/^\s*import\s+[^\n]+$/gm, '');
  const out = [`// Generated by jtr from ${fileName}. Review before production use.`];
  const re = /(?<mods>(?:(?:public|private|protected|internal|open|abstract|sealed)\s+)*)?(?<data>data\s+)?(?<kind>class|interface|object)\s+(?<name>\w+)\s*(?:\((?<params>[^)]*)\))?[^\{]*\{/g;
  let match;
  let found = false;
  while ((match = re.exec(text))) {
    found = true;
    const open = re.lastIndex - 1;
    const bal = extractBalanced(text, open);
    if (!bal) { warnings.push(`Unbalanced Kotlin type ${match.groups.name}`); break; }
    const g = match.groups;
    if (g.kind === 'class') out.push('', convertKotlinClass(g.name, g.mods || '', g.params || '', bal.body, warnings, Boolean(g.data)));
    else if (g.kind === 'interface') out.push('', convertKotlinInterface(g.name, g.mods || '', bal.body, warnings));
    else {
      warnings.push(`Kotlin object ${g.name} converted to a zero-sized Rust struct; singleton semantics need review.`);
      out.push('', `pub struct ${g.name};`);
    }
    re.lastIndex = bal.end + 1;
  }
  if (!found) {
    warnings.push('No top-level Kotlin class/interface/object detected; top-level functions are not fully supported yet.');
    out.push('', '/*', source, '*/');
  }
  return { code: out.join('\n').trim() + '\n', warnings };
}
